# Generated by Django 3.1.7 on 2021-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireTCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('year', models.IntegerField()),
                ('type', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FireType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('ISOCODE', models.TextField(max_length=3)),
                ('UNSDCODE', models.IntegerField()),
                ('CIESINCODE', models.IntegerField()),
                ('Population', models.IntegerField()),
                ('Area_sqkm', models.FloatField()),
            ],
        ),
    ]
