# Generated by Django 3.1.7 on 2021-03-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('ISOCODE', models.TextField(max_length=3)),
                ('UNSDCODE', models.IntegerField()),
                ('CIESINCODE', models.IntegerField()),
                ('Population', models.IntegerField(null=True)),
                ('Area_sqkm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FireTCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fires.region')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fires.firetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='firetcc',
            constraint=models.UniqueConstraint(fields=('region', 'type', 'year'), name='unique_fire'),
        ),
    ]
