# Generated by Django 3.1.7 on 2021-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='Population',
            field=models.IntegerField(null=True),
        ),
    ]
