# Generated by Django 3.1.7 on 2021-03-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0003_auto_20210325_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FireTCC',
        ),
        migrations.DeleteModel(
            name='FireType',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
